### ISSUE TITLE
Remove aromaticity(and probably formal charges and bond orders) from TRP sidechain

### ISSUE THREAD

**Issue by j-wags** [openforcefield/amber-ff-porting#39]
Possibly related to #12 

Under the MDL aromaticity model, the TRP and HIS sidechain rings aren't fully aromatic. To avoid confusion, we should ensure that the FF parameters that are intended to match these sidechains do not match based on aromaticity. In the 0.0.2 release, this isn't an issue for HIS (because that is solved using the resonance trick), but it is for TRP:
```
<Bond smirks="[H]c1c(c(c2[c:2](c1[H])[C:1](=C(N2[H])[H])C([H])([H])[C@@]([H])([C]=O)[N][H])[H])[H]" id="A14SB-MainChain_TRP-C*_CB" length="1.459 * angstrom" k="776.0 * angstrom**-2 * mole**-1 * kilocalorie"></Bond>
```

**Comment by mattwthompson** [comment]
All parameters now lack stereochemistry.
