### ISSUE TITLE
Add CYM parameters

### ISSUE THREAD

**Issue by j-wags** [openforcefield/amber-ff-porting#41]
Following https://github.com/openforcefield/openff-toolkit/issues/1727, some users are interested in also having CYM parameters from ff14SB. I don't have time to do this but I'd guess it'd be relatively straightforward, except that we'd need to make sure it doesn't get jumbled up with CYX.

**Comment by mikemhenry** [comment]
I am going to get this pipeline working locally, then I will setup CI so we can test things using our openeye license. This will be a stopgap until we remove openeye entirely with #43

**Comment by mikemhenry** [comment]
Resolved with #44
